### ISSUE TITLE
Unboud Local Error

### ISSUE THREAD

**Issue by TT-Hipster1941** [musafir-py/Hidden-Friends-Finder#1]
Hi, somehow I've bump into a Unbound Local Error. Have any idea what I did wrong?

Tested on :
Win10 64bits
Chrome Beta 73
ChromeDriver 73.0.3683.68
Python 3.7.2
Facebook profile for test is in english

Every depedencies as been installed :
certifi==2018.11.29
chardet==3.0.4
Click==7.0
colorama==0.4.1
idna==2.8
requests==2.21.0
selenium==3.141.0
tqdm==4.31.1
urllib3==1.24.1
wincertstore==0.2

___________________________________________________________________________________________________________

    ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
    ¶¶¶¶¶¶¶____¶¶¶¶
    ¶¶¶¶¶¶___¶¶¶¶¶¶
    ¶¶¶¶_______¶¶¶¶
    ¶¶¶¶¶¶___¶¶¶¶¶¶
    ¶¶¶¶¶¶___¶¶¶¶¶¶ HIDDEN
    ¶¶¶¶¶¶___¶¶¶¶¶¶ FRIENDS
    ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ FINDER v1.0
    by Musafir.py

Facebook login: ******@*********.com

Facebook password: **********
Target user ID (only numbers): **************

DevTools listening on ws://127.0.0.1:46258/devtools/browser/1dc367db-aa4b-4362-b232-1cc0f2820424
[*] Logging in to facebook account...
[+] Login to facebook account (******@*********.com) successful

[ Verifying data ]
[?] User ID: ************** is connected to profile name: ************** - is this a correct profile? [y/n] y
[*] Data verification in progress. It might take a while...
9it [00:36,  4.04s/it]
[*] Completed. Verified 36 posts with 0 errors.

[ Gathering data ]
[*] Processing reactions
100%|█████████████████████████████████████████████████████████████████| 5/5 [00:26<00:00,  5.21s/it]
[*] Processing comments
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "HFF.py", line 48, in <module>
    main()
  File "C:\Python3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Python3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "HFF.py", line 29, in main
    comment_accounts = core.get_comments(browser)
  File "C:\Users**************\Downloads\Hidden-Friends-Finder-master\modules\core.py", line 135, in get_comments
    for profile in comment_profiles:
UnboundLocalError: local variable 'comment_profiles' referenced before assignment

**Comment by IntelTakes** [comment]
Hi,

Sorry for the delayed reply. Found problem. Somehow forgot to define
comment_profiles variable before loop execution.

Should work now.

Cheers

**Comment by TT-Hipster1941** [comment]
Works flawlessly now! Good job!
