### ISSUE TITLE
crawling very long profile

### ISSUE THREAD

**Issue by lorenzoromani1983** [musafir-py/Hidden-Friends-Finder#2]
This looks interesting, congrats :)

however, after crawling a very long profile with hundreds of posts and thousands of reactions, HFF quit with a Timeout error.
Is it possible to set a limit in the crawling session in order to avoid such an event?

thanks

**Comment by IntelTakes** [comment]
True, hundreds of posts it's a massive amount of code to search through, plus selenium is definitely not a power horse. 
I can use signal to set the time limit for function but it doesn't work in Windows. So I have put the limit of 100 posts to harvest. You can change limit easily in chrome.py file (line 72).
