### ISSUE TITLE
Person Name problem Error saving results - punctuation / paranthesis  signs within profile name

### ISSUE THREAD

**Issue by fiuderazes** [musafir-py/Hidden-Friends-Finder#4]
I get the following errors when saving the positive results for some targets that have different  punctuation signs or paranthesis in their profile name...
 
Printing data ]
[-] Error when writing to file: [Errno 22] Invalid argument: 'Name Surname ( Nickname)-confirmed-friends.csv'
[+] Task completed! 8 confirmed friends saved to Daragiu Constantin
(Dara)-confirmed-friends.csv
[-] Error when writing to file: [Errno 22] Invalid argument: 'Name Surname ( Nickname)-probable-friends.csv'
[+] Task completed! 16 probable friends saved to Name Surname ( Nickname)-probable-friends.csv
Any idea what change can it be done to solve the issued problem? 
If not...is it possible to list the confirmed and unconfirmed friend lists within the terminal, before saving the results?
Thank you for your great work!

**Comment by IntelTakes** [comment]
Thanks for finding this issue! Not all symbols are allowed in file names. Had to change format of the results file to: [target id]-[confirmed/not confirmed]-friends.cvs
